name: Deploy Accelerator

# az ad sp create-for-rbac --name "my-github-action-sp" --role contributor --scopes /subscriptions/4a3b6480-8f2b-41b2-9123-46de70d10895

on:
  push:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Commercial, Government]
        location: [eastus2]
    environment: ${{ matrix.environment }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Replace environment variable tokens
        env:
          GRAPHRAG_API_BASE: ${{ secrets.GRAPHRAG_API_BASE }}
          RESOURCE_GROUP: rg-gr-${{ matrix.environment }}-${{ github.run_number }}
          LOCATION: ${{ matrix.location }}
        run: |
          echo ${${{ matrix.environment }},,}"" | cut -c1-3

          #sed -i 's/__GRAPHRAG_API_BASE__/${{ env.GRAPHRAG_API_BASE }}/g' infra/deploy.parameters.json

          #cat infra/deploy.parameters.json
          cd infra

          cat <<EOF > ci.parameters.json
          {
            "LOCATION": "${{ matrix.location }}",
            "RESOURCE_GROUP": "${{ env.RESOURCE_GROUP }}",
            "GRAPHRAG_API_BASE": "${{ secrets.GRAPHRAG_API_BASE }}",
            "GRAPHRAG_API_VERSION": "${{ secrets.GRAPHRAG_API_VERSION }}",
            "GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME }}",
            "GRAPHRAG_EMBEDDING_MODEL": "${{ secrets.GRAPHRAG_EMBEDDING_MODEL }}",
            "GRAPHRAG_LLM_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_LLM_DEPLOYMENT_NAME }}",
            "GRAPHRAG_LLM_MODEL": "${{ secrets.GRAPHRAG_LLM_MODEL }}"
          }
          EOF
          cat ci.parameters.json

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
