name: Deploy Accelerator

on:
  push:
  workflow_dispatch:

jobs:

  deploy:
    environment: Commercial
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    environment: [Commercial, Government]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Replace environment variable tokens
        run: |
          #sed -i 's/__GRAPHRAG_API_BASE__/asdfasdfasdf/g' infra/deploy.parameters.json
          sed -i 's/__GRAPHRAG_API_BASE__/"${{ secrets.GRAPHRAG_API_BASE }}"/g' infra/deploy.parameters.json
          # sed -i 's/{{SECRET_KEY}}/${{ secrets.SECRET_KEY }}/g' infra/deploy.parameters.json
          cat infra/deploy.parameters.json

      - name: Print deploy.parameters.json
        run: cat infra/deploy.parameters.json
