name: Deploy Accelerator

on:
  push:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Commercial, Government]
    environment: ${{ matrix.environment }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Replace environment variable tokens
        env:
          GRAPHRAG_API_BASE: ${{ secrets.GRAPHRAG_API_BASE }}
          RESOURCE_GROUP: rg-gr-${{ matrix.environment }}-${{ github.run_number }}
        run: |
          #sed -i 's/__GRAPHRAG_API_BASE__/${{ env.GRAPHRAG_API_BASE }}/g' infra/deploy.parameters.json

          #cat infra/deploy.parameters.json
          cd infra
          echo "{}" >> ci.parameters.json
          ./deploy.sh -p ci.parameters.json
