name: Deploy Accelerator

# az ad sp create-for-rbac --name "my-github-action-sp" --role contributor --scopes /subscriptions/4a3b6480-8f2b-41b2-9123-46de70d10895

on:
  push:
  workflow_dispatch:

jobs:

  a:
    if: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # I hate this - how do i move location info to env vars?
        include:
          - environment: Commercial
            location: eastus2
          - environment: Commercial
            location: westus2
          - environment: Government
            location: usgovvirginia
          - environment: Government
            location: usgovarizona

    environment: ${{ matrix.environment }}

    env:
      RESOURCE_GROUP_STUB: rg-grci-${{ github.run_number }}
      RESOURCE_GROUP: ""
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        if: ${{ matrix.environment == 'Commercial' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Government
        if: ${{ matrix.environment == 'Government' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'azureusgovernment'

      - name: Create resource group and assign RBAC
        run: |
          ENV_TRUNC=${{ matrix.environment }}
          ENV_TRUNC=${ENV_TRUNC:0:3}
          RESOURCE_GROUP=$RESOURCE_GROUP_STUB-$ENV_TRUNC-${{ matrix.location }}

          echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> "$GITHUB_ENV"

          rgId=$(az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ matrix.location }} --query id -o tsv)
          appId=$(az ad sp list --display-name github-action-sp --query [].appId -o tsv)

          az role assignment create --role "Owner" --assignee $appId --scope $rgId

      - name: Get special gov env variables
        if: ${{ matrix.environment == 'Government' }}
        run: |
          cd infra
          cat <<EOF > gov.tmp.env

            "CLOUD_NAME": "AzureUSGovernment",
            "AISEARCH_ENDPOINT_SUFFIX": "search.azure.us",
            "AISEARCH_AUDIENCE": "https://search.azure.us",
            "GRAPHRAG_COGNITIVE_SERVICES_ENDPOINT":"https://cognitiveservices.azure.us/.default",

          EOF


      - name: Replace environment variable tokens
        run: |
          cd infra

          touch gov.tmp.env

          cat <<EOF > ci.parameters.json
          {
            $( cat gov.tmp.env )
            "LOCATION": "${{ matrix.location }}",
            "RESOURCE_GROUP": "${{ env.RESOURCE_GROUP }}",
            "GRAPHRAG_API_BASE": "${{ secrets.GRAPHRAG_API_BASE }}",
            "GRAPHRAG_API_VERSION": "${{ secrets.GRAPHRAG_API_VERSION }}",
            "GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME }}",
            "GRAPHRAG_EMBEDDING_MODEL": "${{ secrets.GRAPHRAG_EMBEDDING_MODEL }}",
            "GRAPHRAG_LLM_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_LLM_DEPLOYMENT_NAME }}",
            "GRAPHRAG_LLM_MODEL": "${{ secrets.GRAPHRAG_LLM_MODEL }}"
          }
          EOF
          cat ci.parameters.json

      - name: Deploy Accelerators
        run: |
          cd infra
          ./deploy.sh -g -p ci.parameters.json

      - name: Clean up
        if: always()
        run: |
          #echo Hi
          az group delete --name ${{ env.RESOURCE_GROUP }} --yes --no-wait


  test-login:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Commercial, Government]
    environment: ${{ matrix.environment }}
    steps:
      - name: Log in to Azure
        if: ${{ matrix.environment == 'Commercial' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Government
        if: ${{ matrix.environment == 'Government' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'azureusgovernment'

      - name: print out rgs
        run: |
          az group list -o table

  test:
    if: false
    runs-on: ubuntu-latest
    needs: test-login
    strategy:
      matrix:
        environment: [Commercial, Government]
    environment: ${{ matrix.environment }}
    steps:
      - name: Replace environment variable tokens
        env:
          TIM: "Tim"
        run: |
          echo $TIM
          echo "${{ vars.LOCATIONS }}" >> tmp.txt

          cat tmp.txt

  set-env:
    runs-on: ubuntu-latest
    if: false
    outputs:
      locations: ${{ steps.set-output.outputs.locations }}
    strategy:
      matrix:
        environment: [Commercial, Government]
    environment: ${{ matrix.environment }}

    steps:
      - name: Set locations
        id: set-output
        run: echo "locations=${{ vars.LOCATIONS }}" >> $GITHUB_OUTPUT

  matrix-test:
    runs-on: ubuntu-latest
    if: false
    needs: [set-env]
    strategy:
      matrix:
        environment: [Commercial, Government]
    environment: ${{ matrix.environment }}
    env:
      LOCATIONS: ${{ needs.set-env.outputs.locations }}
    steps:
      - name: Replace environment variable tokens
        run: |
          echo "Hello"
          echo $LOCATIONS
          echo "World"

  deploy:
    if: false
    runs-on: ubuntu-latest
    needs: [test-login, set-env, test]
    strategy:
      matrix:
        environment: [Commercial]
        location: ${{ fromJSON (needs.set-env.outputs.locations) }}
    environment: ${{ matrix.environment }}
    env:
      RESOURCE_GROUP: rg-grci-${{ github.run_number }}-${{ matrix.environment }}-${{ matrix.location }}
      LOCATION: ${{ matrix.location }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group and assign RBAC
        run: |
          rgId=$(az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }} --query id -o tsv)
          appId=$(az ad sp list --display-name github-action-sp --query [].appId -o tsv)

          az role assignment create --role "Owner" --assignee $appId --scope $rgId

      - name: Replace environment variable tokens
        env:
          TIM: "Tim"
          #RESOURCE_GROUP: rg-gr-${{ matrix.environment }}-${{ github.run_number }}
          #LOCATION: ${{ matrix.location }}
        run: |
          cd infra

          cat <<EOF > ci.parameters.json
          {
            "LOCATION": "${{ matrix.location }}",
            "RESOURCE_GROUP": "${{ env.RESOURCE_GROUP }}",
            "GRAPHRAG_API_BASE": "${{ secrets.GRAPHRAG_API_BASE }}",
            "GRAPHRAG_API_VERSION": "${{ secrets.GRAPHRAG_API_VERSION }}",
            "GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME }}",
            "GRAPHRAG_EMBEDDING_MODEL": "${{ secrets.GRAPHRAG_EMBEDDING_MODEL }}",
            "GRAPHRAG_LLM_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_LLM_DEPLOYMENT_NAME }}",
            "GRAPHRAG_LLM_MODEL": "${{ secrets.GRAPHRAG_LLM_MODEL }}"
          }
          EOF
          cat ci.parameters.json

      - name: Deploy Accelerators
        run: |
          cd infra
          ./deploy.sh -g -p ci.parameters.json

      - name: Clean up
        if: always()
        run: |
          echo Hi
          #az group delete --name ${{ env.RESOURCE_GROUP }} --yes --no-wait
