name: Deploy Accelerator

# az ad sp create-for-rbac --name "my-github-action-sp" --role contributor --scopes /subscriptions/4a3b6480-8f2b-41b2-9123-46de70d10895

on:
  push:
  workflow_dispatch:

jobs:

  deploy-accelerator:
    if: true
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        # I hate this - how do i move location info to env vars?
        environment: [Commercial, Government]
        dev-mode: [-g]
        location: [eastus2, westus2, usgovarizona]
        exlude:
          - environment: Government
            location: eastus2
          - environment: Government
            location: westus2
          - environment: Commercial
            location: usgovarizona

    environment: ${{ matrix.environment }}

    env:
      RESOURCE_GROUP_STUB: rg-grci-${{ github.run_number }}
      #RESOURCE_GROUP: ""
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        if: ${{ matrix.environment == 'Commercial' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Government
        if: ${{ matrix.environment == 'Government' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'azureusgovernment'

      - name: Create resource group and assign RBAC
        run: |
          ENV_TRUNC=${{ matrix.environment }}
          ENV_TRUNC=${ENV_TRUNC:0:3}
          export RESOURCE_GROUP=$RESOURCE_GROUP_STUB-$ENV_TRUNC-${{ matrix.location }}

          echo "RESOURCE_GROUP=$RESOURCE_GROUP" >> "$GITHUB_ENV"

          rgId=$(az group create --name $RESOURCE_GROUP --location ${{ matrix.location }} --query id -o tsv)
          appId=$(az ad sp list --display-name github-action-sp --query [].appId -o tsv)

          az role assignment create --role "Owner" --assignee $appId --scope $rgId

      - name: Get special gov env variables
        if: ${{ matrix.environment == 'Government' }}
        run: |
          cd infra
          cat <<EOF > gov.tmp.env

            "CLOUD_NAME": "AzureUSGovernment",
            "AISEARCH_ENDPOINT_SUFFIX": "search.azure.us",
            "AISEARCH_AUDIENCE": "https://search.azure.us",
            "GRAPHRAG_COGNITIVE_SERVICES_ENDPOINT":"https://cognitiveservices.azure.us/.default",

          EOF


      - name: Replace environment variable tokens
        run: |
          cd infra

          touch gov.tmp.env

          cat <<EOF > ci.parameters.json
          {
            $( cat gov.tmp.env )
            "LOCATION": "${{ matrix.location }}",
            "RESOURCE_GROUP": "$RESOURCE_GROUP",
            "GRAPHRAG_API_BASE": "${{ secrets.GRAPHRAG_API_BASE }}",
            "GRAPHRAG_API_VERSION": "${{ secrets.GRAPHRAG_API_VERSION }}",
            "GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME }}",
            "GRAPHRAG_EMBEDDING_MODEL": "${{ secrets.GRAPHRAG_EMBEDDING_MODEL }}",
            "GRAPHRAG_LLM_DEPLOYMENT_NAME": "${{ secrets.GRAPHRAG_LLM_DEPLOYMENT_NAME }}",
            "GRAPHRAG_LLM_MODEL": "${{ secrets.GRAPHRAG_LLM_MODEL }}"
          }
          EOF
          cat ci.parameters.json

      - name: Deploy Accelerators
        run: |
          cd infra
          ./deploy.sh ${{ matrix.dev-mode }} -p ci.parameters.json

      - name: Obtain APIM keys
        run: |

          APIM_NAME="$(az apim list --resource-group $RESOURCE_GROUP --query "[0].name" -o tsv)"
          SUBSCRIPTION_ID=$(az account show --query id --output tsv)
          API_VERSION="2022-08-01"

          if [ "${{ matrix.environment }}" == "Commercial" ]; then
            MANAGEMENT_URL="https://management.azure.com"
          else
            MANAGEMENT_URL="https://management.usgovcloudapi.net"
          fi

          URL="${MANAGEMENT_URL}/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.ApiManagement/service/${APIM_NAME}/subscriptions/master/listSecrets?api-version=${API_VERSION}"

          az rest --method POST --uri $URL --query "primaryKey" -o tsv

      - name: Clean up
        if: always()
        run: |
          #echo Hi
          az group delete --name $RESOURCE_GROUP --yes --no-wait
